version: "3"
services:
  app:
    container_name: amplify_handson_container
    build:
      context: ./docker
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    volumes:
      - ./src:/usr/src/app